version: "3.8"
services:
  localstack:
    image: localstack/localstack
    environment:
      - SERVICES=s3,dynamodb,lambda,apigateway
      - DEBUG=1
      - AWS_DEFAULT_REGION=us-east-1
    ports:
      - "4566:4566"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
